version: "3"

services:
  pg-chat:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: chat
  server:
    build: ./
    ports:
      - "3456:3000"
    environment:
      TYPEORM_URL: postgres://postgres:postgres@pg-chat:5432/chat
